[package]
name = "ipelfs"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
sys-info = "0.9"
clap = { version = "4.5", features = ["derive"] }
