[package]
name = "ipelfs"
version = "2.1.3"
edition = "2024"

[dependencies]
axum = "0.8" #
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
chrono = "0.4"